name: Run Android UI Tests
on:
  pull_request:
    paths:
      - "android/**"
      - "shared/**"
      - "buildSrc/**"
      - ".github/workflows/android-ui-test.yml"
  push:
    branches:
      - development
    paths:
      - "android/**"
      - "shared/**"
      - "buildSrc/**"
      - ".github/workflows/android-ui-test.yml"
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > ./android/app-project-newm/google-services.json

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          profile: pixel_4_xl
          script: adb shell settings put global hidden_api_policy_p_apps 1 && adb shell settings put global hidden_api_policy_pre_p_apps 1 && ./gradlew debugExecuteScreenshotTests
