on:
  pull_request:
    paths:
      - "androidApp/**"
      - "shared/**"
      - "buildSrc/**"
      - ".github/workflows/android-ui-test.yml"
  push:
    branches:
      - development
    paths:
      - "androidApp/**"
      - "shared/**"
      - "buildSrc/**"
      - ".github/workflows/android-ui-test.yml"
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > ./androidApp/google-services.json
      
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
