name: Record Android screenshots
on:
  pull_request:
  workflow_dispatch:

jobs:
  record_screenshots:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > ./android/app-project-newm/google-services.json

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          profile: Nexus 6
          script: adb shell settings put global hidden_api_policy_p_apps 1 && adb shell settings put global hidden_api_policy_pre_p_apps 1 && ./gradlew debugExecuteScreenshotTests -Precord

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: ${{ github.head_ref }}
