name: Distribute Android App
on:
  push:
    branches:
      - development
    paths:
      - "android/**"
      - "shared/**"
      - "buildSrc/**"
      - ".github/workflows/android-preview-branch-merge.yml"
jobs:
  build_android_debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > ./android/app-project-newm/google-services.json

      - name: build android app
        run: ./gradlew :app-project-newm:assembleDebug

      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: android/app-project-newm/build/outputs/apk/debug/androidApp-debug.apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: dev-team
          file: android/app-project-newm/build/outputs/apk/debug/androidApp-debug.apk
