name: iOS Testing
on:
  pull_request:
    branches:
    - development
    - master
    paths:
    - '.github/**'
    - 'build.gradle.kts'
    - 'gradle/**'
    - 'gradle.properties'
    - 'gradlew.bat'
    - 'iosApp/**'
    - 'local.properties'
    - 'settings.gradle.kts'
    - 'shared/build/xcode-frameworks/**'
    - 'shared/src/commonMain/**'
    - 'shared/src/iosMain/**'
    - 'shared/build.gradle.kts'
jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
