name: iOS Testing
on:
  pull_request:
    branches:
      - development
      - master
    paths:
      - '.github/**'
      - 'build.gradle.kts'
      - 'gradle/**'
      - 'gradle.properties'
      - 'gradlew.bat'
      - 'iosApp/**'
      - 'local.properties'
      - 'settings.gradle.kts'
      - 'shared/build/xcode-frameworks/**'
      - 'shared/src/commonMain/**'
      - 'shared/src/iosMain/**'
      - 'shared/build.gradle.kts'

jobs:
  test:
    name: Test iOS App
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode 16.2
        uses: actions/setup-xcode@v3
        with:
          xcode-version: '16.2'

      - name: Run iOS app tests
        run: exec ./.github/scripts/test_app.sh
